import { Scheme } from "./types"

export const SAMPLE_SCHEMES: Omit<Scheme, "id" | "created_at">[] = [
  {
    name: "PM Kisan Samman Nidhi",
    description: "Direct income support of Rs 6,000 per year to farmer families in three equal installments.",
    ministry: "Ministry of Agriculture",
    eligibility_criteria: { land_owner: true },
    benefits: "Rs 6,000 per year direct bank transfer",
    application_url: "https://pmkisan.gov.in",
    documents_required: ["Aadhaar Card", "Land Records", "Bank Account Details"],
    category: "Agriculture",
    target_audience: ["farmer"],
    min_age: 18,
    max_age: null,
    min_income: null,
    max_income: null,
    applicable_states: [],
    applicable_categories: ["general", "obc", "sc", "st", "ews"],
  },
  {
    name: "PM Awas Yojana (Urban)",
    description: "Affordable housing scheme providing financial assistance for construction or enhancement of houses.",
    ministry: "Ministry of Housing & Urban Affairs",
    eligibility_criteria: { no_pucca_house: true },
    benefits: "Subsidy up to Rs 2.67 Lakh on home loan interest",
    application_url: "https://pmaymis.gov.in",
    documents_required: ["Aadhaar Card", "Income Certificate", "Address Proof", "Bank Statement"],
    category: "Housing",
    target_audience: ["general", "job_seeker"],
    min_age: 21,
    max_age: 65,
    min_income: null,
    max_income: 1800000,
    applicable_states: [],
    applicable_categories: ["general", "obc", "sc", "st", "ews"],
  },
  {
    name: "National Scholarship Portal",
    description: "Single-window electronic platform for students to apply for various scholarships.",
    ministry: "Ministry of Education",
    eligibility_criteria: { enrolled_student: true },
    benefits: "Scholarships ranging from Rs 5,000 to Rs 50,000 annually",
    application_url: "https://scholarships.gov.in",
    documents_required: ["Aadhaar Card", "Income Certificate", "Academic Records", "Bank Account"],
    category: "Education",
    target_audience: ["student"],
    min_age: 16,
    max_age: 35,
    min_income: null,
    max_income: 800000,
    applicable_states: [],
    applicable_categories: ["obc", "sc", "st", "ews"],
  },
  {
    name: "Startup India Initiative",
    description: "Support for startups with tax benefits, easier compliance, and funding opportunities.",
    ministry: "Ministry of Commerce & Industry",
    eligibility_criteria: { registered_startup: true },
    benefits: "Tax exemption for 3 years, easier compliance, funding access",
    application_url: "https://www.startupindia.gov.in",
    documents_required: ["Company Registration", "Business Plan", "PAN Card", "Aadhaar of Founders"],
    category: "Business",
    target_audience: ["business_owner"],
    min_age: 18,
    max_age: null,
    min_income: null,
    max_income: null,
    applicable_states: [],
    applicable_categories: ["general", "obc", "sc", "st", "ews"],
  },
  {
    name: "PM Employment Generation Programme",
    description: "Generate self-employment opportunities through establishment of micro-enterprises.",
    ministry: "Ministry of MSME",
    eligibility_criteria: { project_cost_limit: true },
    benefits: "Margin money subsidy up to 35% for rural & 25% for urban areas",
    application_url: "https://www.kviconline.gov.in",
    documents_required: ["Aadhaar Card", "Education Certificates", "Project Report", "Caste Certificate"],
    category: "Employment",
    target_audience: ["job_seeker", "business_owner"],
    min_age: 18,
    max_age: null,
    min_income: null,
    max_income: null,
    applicable_states: [],
    applicable_categories: ["general", "obc", "sc", "st", "ews"],
  },
  {
    name: "Ayushman Bharat - PMJAY",
    description: "Health insurance scheme providing coverage up to Rs 5 Lakh per family per year.",
    ministry: "Ministry of Health & Family Welfare",
    eligibility_criteria: { below_poverty_line: true },
    benefits: "Free health insurance coverage up to Rs 5 Lakh per family",
    application_url: "https://pmjay.gov.in",
    documents_required: ["Aadhaar Card", "Ration Card", "Income Certificate"],
    category: "Healthcare",
    target_audience: ["general", "farmer", "job_seeker"],
    min_age: null,
    max_age: null,
    min_income: null,
    max_income: 500000,
    applicable_states: [],
    applicable_categories: ["sc", "st", "ews"],
  },
  {
    name: "Mudra Yojana",
    description: "Loans up to Rs 10 Lakh to non-corporate, non-farm small/micro enterprises.",
    ministry: "Ministry of Finance",
    eligibility_criteria: { small_business: true },
    benefits: "Collateral-free loans: Shishu (up to 50K), Kishore (50K-5L), Tarun (5L-10L)",
    application_url: "https://www.mudra.org.in",
    documents_required: ["Identity Proof", "Address Proof", "Business Plan", "Quotation of Machinery"],
    category: "Business",
    target_audience: ["business_owner", "job_seeker"],
    min_age: 18,
    max_age: 65,
    min_income: null,
    max_income: null,
    applicable_states: [],
    applicable_categories: ["general", "obc", "sc", "st", "ews"],
  },
  {
    name: "Sukanya Samriddhi Yojana",
    description: "Small savings scheme for the girl child with high interest rate and tax benefits.",
    ministry: "Ministry of Finance",
    eligibility_criteria: { girl_child: true },
    benefits: "7.6% interest rate, tax exemption under 80C",
    application_url: "https://www.indiapost.gov.in",
    documents_required: ["Birth Certificate of Girl Child", "Guardian ID Proof", "Address Proof"],
    category: "Savings",
    target_audience: ["general"],
    min_age: null,
    max_age: 10,
    min_income: null,
    max_income: null,
    applicable_states: [],
    applicable_categories: ["general", "obc", "sc", "st", "ews"],
  },
  {
    name: "Atal Pension Yojana",
    description: "Pension scheme for workers in the unorganized sector ensuring minimum pension.",
    ministry: "Ministry of Finance",
    eligibility_criteria: { unorganized_sector: true },
    benefits: "Guaranteed pension of Rs 1,000 to Rs 5,000 per month after 60 years",
    application_url: "https://www.npscra.nsdl.co.in/nsdl-apy.php",
    documents_required: ["Aadhaar Card", "Bank Account", "Mobile Number"],
    category: "Pension",
    target_audience: ["farmer", "job_seeker", "general"],
    min_age: 18,
    max_age: 40,
    min_income: null,
    max_income: null,
    applicable_states: [],
    applicable_categories: ["general", "obc", "sc", "st", "ews"],
  },
  {
    name: "Stand-Up India",
    description: "Loans between Rs 10 Lakh to Rs 1 Crore for SC/ST and women entrepreneurs.",
    ministry: "Ministry of Finance",
    eligibility_criteria: { sc_st_women: true },
    benefits: "Composite loan for greenfield enterprises in manufacturing or services",
    application_url: "https://www.standupmitra.in",
    documents_required: ["Caste Certificate", "Business Plan", "ID Proof", "Address Proof"],
    category: "Business",
    target_audience: ["business_owner"],
    min_age: 18,
    max_age: null,
    min_income: null,
    max_income: null,
    applicable_states: [],
    applicable_categories: ["sc", "st"],
  },
  {
    name: "PM Vishwakarma Yojana",
    description: "Support for traditional artisans and craftspeople with skills, tools, and credit.",
    ministry: "Ministry of MSME",
    eligibility_criteria: { traditional_craftsperson: true },
    benefits: "Skill training, toolkit worth Rs 15,000, collateral-free loans up to Rs 3 Lakh",
    application_url: "https://pmvishwakarma.gov.in",
    documents_required: ["Aadhaar Card", "Bank Account", "Mobile Number", "Skill Certificate"],
    category: "Skills",
    target_audience: ["general", "job_seeker"],
    min_age: 18,
    max_age: null,
    min_income: null,
    max_income: null,
    applicable_states: [],
    applicable_categories: ["general", "obc", "sc", "st", "ews"],
  },
  {
    name: "Kisan Credit Card",
    description: "Credit facility for farmers to meet agricultural and allied activities needs.",
    ministry: "Ministry of Agriculture",
    eligibility_criteria: { farmer: true },
    benefits: "Low interest credit up to Rs 3 Lakh at 4% interest rate",
    application_url: "https://pmkisan.gov.in",
    documents_required: ["Land Records", "Aadhaar Card", "Passport Photo", "Address Proof"],
    category: "Agriculture",
    target_audience: ["farmer"],
    min_age: 18,
    max_age: 75,
    min_income: null,
    max_income: null,
    applicable_states: [],
    applicable_categories: ["general", "obc", "sc", "st", "ews"],
  },
]
